"use client";
import { useEffect, useState } from "react";
import QuoteStrip from "./quote-strip";
import { ArrowUpRight, BookOpen, CalendarDays, HeartHandshake, Menu, Play, Sparkles, UsersRound, X } from "lucide-react";

const wings = [
  ["Spiritual Care", "Sadhana", "Bhajans, study circles, retreats and a daily practice rooted in love.", Sparkles, "gold"],
  ["Bal Vikas & Educare", "Education", "Human values education for children, parents, gurus and schools.", BookOpen, "blue"],
  ["Socio Care", "Service", "Narayana Seva, healthcare, water, disaster response and community care.", HeartHandshake, "coral"],
  ["Sai Youth", "Youth", "Young people leading with courage, compassion and practical service.", UsersRound, "violet"],
  ["Mahila Vibhag", "Women", "A space for women to connect, serve and grow together in the mission.", Sparkles, "green"],
] as const;
const districts = ["Anakapalli", "Anantapur", "Bapatla", "Chittoor", "Guntur", "Kakinada", "Krishna", "Nellore", "Prakasam", "Sri Sathya Sai", "Srikakulam", "Visakhapatnam", "Vizianagaram", "West Godavari"];
const heroWords = ["LOVE", "SEVA", "SADHANA", "EDUCARE", "UNITY", "COMPASSION"];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => setLoading(false), 4200); return () => window.clearTimeout(timer); }, []);
  return <main className="site-shell">
    {loading && <div className="welcome-screen" role="status" aria-live="polite"><div className="welcome-grid" /><div className="welcome-halo" /><div className="welcome-logo"><img src="/ssssoap_logo.jpeg" alt="SSSSO Andhra Pradesh" /></div><div className="namaskaram" aria-hidden="true"><span>🙏</span></div><div className="welcome-kicker">SRI SATHYA SAI SEVA ORGANISATION</div><h1>Welcome to <em>SSSSO AP</em></h1><p>Love all · Serve all</p><div className="loading-track"><span /></div><small>Preparing a space for service</small></div>}
    <div className="announcement"><span className="pulse-dot" /> Serving through love in Andhra Pradesh <span className="announcement-link">Explore our work <ArrowUpRight size={14} /></span></div>
    <header className="nav-wrap"><a href="#top" className="brand"><span className="brand-mark"><img src="/ssssoap_logo.jpeg" alt="" /></span><span><strong>SSSSO</strong><small>Andhra Pradesh</small></span></a><nav className={menuOpen ? "nav-links open" : "nav-links"}>{[["About", "/about"], ["Our wings", "/wings"], ["Initiatives", "/initiatives"], ["Districts", "/districts"], ["Resources", "/resources"]].map(([label, href]) => <a href={href} key={label} onClick={() => setMenuOpen(false)}>{label}</a>)}<a href="/get-involved" className="nav-cta" onClick={() => setMenuOpen(false)}>Get involved <ArrowUpRight size={16} /></a></nav><div className="nav-actions"><button className="menu-button" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div></header>
    <section className="hero" id="top"><div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="hero-particles">{[...Array(18)].map((_, i) => <i key={i} style={{ left: `${(i * 37) % 100}%`, top: `${(i * 53) % 100}%`, animationDelay: `${i * .23}s` }} />)}</div><div className="hero-copy"><div className="eyebrow"><span /> Sri Sathya Sai Seva Organisation</div><h1>Love in action.<br /><em>Service as a way of life.</em></h1><p>Inspired by Bhagawan Sri Sathya Sai Baba, we bring together people across Andhra Pradesh to serve, learn and grow in unity.</p><div className="hero-actions"><a href="/wings" className="button button-primary">Discover our work <ArrowUpRight size={17} /></a><a href="/initiatives" className="text-link"><span className="play-icon"><Play size={12} fill="currentColor" /></span> See our impact</a></div><div className="hero-note"><div className="mini-avatars"><span>ॐ</span><span>♥</span><span>✦</span></div><span>One mission, many hands.<br /><strong>Serving every community with love.</strong></span></div><div className="hero-signal"><span><strong>26</strong> districts</span><span><strong>05</strong> service wings</span><span><strong>∞</strong> possibilities</span></div></div><div className="hero-art"><div className="hero-word-orbit">{heroWords.map((word, i) => <span key={word} style={{ transform: `rotate(${i * 60}deg) translateY(-215px) rotate(-${i * 60}deg)`, animationDelay: `${i * .2}s` }}>{word}</span>)}</div><div className="sun-disc"><div className="sun-core">ॐ</div><div className="orbit orbit-a" /><div className="orbit orbit-b" /></div><div className="art-card card-top"><Sparkles size={18} /><span>Inner transformation</span></div><div className="art-card card-bottom"><HeartHandshake size={18} /><span>Selfless service</span></div><div className="art-caption"><span className="caption-line" /><span>Andhra Pradesh · Since 1965</span></div></div><div className="scroll-cue"><span /> Scroll to explore</div></section>
    <section className="intro section-pad" id="about"><div className="section-kicker">A living mission</div><div className="intro-grid"><h2>When we serve others,<br /><span>we serve the divine in all.</span></h2><div><p className="lead">The Organisation is a spiritual movement with service at its heart. Across every district, volunteers turn values into action through education, healthcare, community care and inner development.</p><a className="text-link dark" href="/wings">Learn about SSSSO AP <ArrowUpRight size={16} /></a></div></div><div className="stat-strip"><div><strong>26</strong><span>Districts in AP</span></div><div><strong>5</strong><span>Wings of service</span></div><div><strong>∞</strong><span>Hands in action</span></div><div><strong>9</strong><span>Point code of conduct</span></div></div></section>
    <section className="wings-section section-pad" id="wings"><div className="section-heading"><div><div className="section-kicker">Five paths, one purpose</div><h2>Our wings of <span>service</span></h2></div><a href="/get-involved" className="text-link dark">View all areas <ArrowUpRight size={16} /></a></div><div className="wings-grid">{wings.map(([label, eyebrow, text, Icon, tone], i) => <article className={`wing-card tone-${tone}`} key={label}><div className="wing-top"><span className="wing-number">0{i + 1}</span><span className="wing-icon"><Icon size={20} /></span></div><div><div className="card-eyebrow">{eyebrow}</div><h3>{label}</h3><p>{text}</p></div><a href="/initiatives" aria-label={`Explore ${label}`}><ArrowUpRight size={18} /></a></article>)}</div></section>
    <section className="impact-section section-pad" id="initiatives"><div className="impact-copy"><div className="section-kicker light">Service in motion</div><h2>Small acts.<br /><em>Far-reaching light.</em></h2><p>From a glass of clean water to a child learning human values, each initiative carries the same simple promise: leave every life a little brighter.</p><a href="/resources" className="button button-light">Explore initiatives <ArrowUpRight size={17} /></a></div><div className="impact-collage"><div className="collage-main"><div className="collage-sun">✦</div><span>Service is the life breath<br />of the Organisation.</span></div><div className="collage-small small-one"><span>MEDICARE</span><strong>Care for every body</strong></div><div className="collage-small small-two"><span>EDUCARE</span><strong>Values for every child</strong></div><div className="collage-ring" /></div></section>
    <section className="district-section section-pad" id="districts"><div className="section-heading"><div><div className="section-kicker">Connected by seva</div><h2>Across Andhra <span>Pradesh</span></h2></div><a href="/get-involved" className="text-link dark">Find your district <ArrowUpRight size={16} /></a></div><div className="district-layout"><div className="district-map"><div className="map-outline"><span className="map-label">AP</span>{[...Array(12)].map((_, i) => <i key={i} style={{ left: `${24 + i * 5.4}%`, top: `${15 + ((i * 17) % 68)}%` }} />)}</div><div className="map-caption"><span className="pulse-dot" /> District presence grows through every volunteer</div></div><div className="district-list">{districts.map((district, i) => <a href="/get-involved" key={district}><span>{String(i + 1).padStart(2, "0")}</span>{district}<ArrowUpRight size={15} /></a>)}</div></div></section>
    <section className="resources-section section-pad" id="resources"><div className="section-kicker">Stay connected</div><div className="resource-grid"><div className="resource-intro"><h2>There is always a way to <span>participate.</span></h2><p>Read the latest circulars, join an event, find learning resources or connect with your nearest Samithi.</p><a href="/get-involved" className="button button-primary">Find your next step <ArrowUpRight size={17} /></a></div><div className="resource-list"><a href="/get-involved"><div className="resource-icon"><CalendarDays size={19} /></div><div><span>Events & reports</span><small>See what is happening near you</small></div><ArrowUpRight size={18} /></a><a href="/get-involved"><div className="resource-icon"><BookOpen size={19} /></div><div><span>Learning resources</span><small>Bal Vikas, Educare and more</small></div><ArrowUpRight size={18} /></a><a href="/get-involved"><div className="resource-icon"><UsersRound size={19} /></div><div><span>Connect with us</span><small>Districts, contacts and volunteering</small></div><ArrowUpRight size={18} /></a></div></div></section>
    <QuoteStrip/><footer id="contact"><div className="footer-main"><div><a href="#top" className="brand footer-brand"><span className="brand-mark">ॐ</span><span><strong>SSSSO</strong><small>Andhra Pradesh</small></span></a><p>Love all. Serve all.<br />Help ever. Hurt never.</p></div><div className="footer-links"><div><span>Explore</span><a href="/about">About us</a><a href="/wings">Our wings</a><a href="/districts">Districts</a></div><div><span>Resources</span><a href="/initiatives">Initiatives</a><a href="/resources">Events & reports</a><a href="/resources">Learning centre</a></div><div><span>Connect</span><a href="/get-involved">Contact office</a><a href="/get-involved">Volunteer with us</a><a href="/get-involved">Coordinator login</a></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Sri Sathya Sai Seva Organisation, Andhra Pradesh</span><span>Powered by <a href="https://visionariesai.com" target="_blank" rel="noreferrer">VisionariesAI Labs Private Limited</a> · <a href="/get-involved">Privacy & terms</a></span></div></footer>
  </main>;
}
